### ISSUE TITLE
Gives  `TypeError` with Laravel-Nova-Excel export

### ISSUE THREAD

**Issue by itsdanielfelix** [zepfietje/laravel-seeable#1]
Gives 500 status code and `TypeError` when exporting the data as excel.

`ZepFietje\Seeable\Http\Middleware\SeeUser::handle(): Return value must be of type Illuminate\Http\Response|Illuminate\Http\RedirectResponse|Illuminate\Http\JsonResponse, Symfony\Component\HttpFoundation\BinaryFileResponse returned`

![laravel-seeable-01](https://user-images.githubusercontent.com/28915352/181189599-fe5e1784-632c-4743-b80d-d1d901fe1cd0.png)
![laravel-seeable-02](https://user-images.githubusercontent.com/28915352/181189630-7653e96e-4c6e-4ed9-8a66-13d9c05146ff.png)
![laravel-seeable-03](https://user-images.githubusercontent.com/28915352/181189647-51319aab-e57b-4977-9a19-258e6f845b9e.png)

**Comment by zepfietje** [comment]
Fixed in [0.3.1](https://github.com/zepfietje/laravel-seeable/releases/tag/0.3.1)!
